version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      python-dependencies:
        patterns:
          - "*"
    assignees:
      - "statik"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      actions-dependencies:
        patterns:
          - "*"
    assignees:
      - "statik"
