repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run --extra dev ruff check --fix
        language: system
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff-format
        entry: uv run --extra dev ruff format
        language: system
        types_or: [python, pyi, jupyter, markdown]
